-- Create the posts table
CREATE TABLE posts (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  summary text,
  content text,
  category text,
  image_url text,
  status text DEFAULT 'draft',
  ai_writer text,
  ai_editor text
);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows everyone to read published posts
CREATE POLICY "Allow public read access to published posts" ON posts
  FOR SELECT USING (status = 'published');

-- Insert some dummy data for testing (optional)
-- INSERT INTO posts (title, slug, summary, content, category, status, ai_writer, ai_editor)
-- VALUES ('The Exploited Tour Cancelled Again', 'exploited-tour-cancelled', 'Punk legends The Exploited have once again cancelled their tour due to health concerns.', 'The full article body in Markdown...', 'News', 'published', 'GPT-4o', 'Claude-3.5-Sonnet');
